package com.rlapcs.radiotransfer;

import net.minecraftforge.common.config.Config;

/**
 * Access point for user-configurable mod values.
 * Config file will be autogenerated by forge, with default values as are here.
 */
@Config(modid = RadioTransfer.MODID)
@Config.LangKey("radiotransfer.config.title") //why "title?"
public class ModConfig {
    @Config.Comment("Verifies that this this config matches the version of RadioTransfer you are using. Internal use only (unless you know what you're doing).")
    public static double config_version = 1.0;

    public static PowerConfig power_options = new PowerConfig();
    public static class PowerConfig {
        public Radio radio = new Radio();
        public static class Radio {
            @Config.Comment("Constant Power Usage of Radio Block (FE/t)")
            @Config.RangeInt(min = 0, max = 1000)
            public int powerPerTick = 10;
        }
        public TXController tx_controller = new TXController();
        public static class TXController {
            @Config.Comment("Base Constant Power Usage of TX Controller (FE/t)")
            @Config.RangeInt(min = 0, max = 1000)
            public int basePowerPerTick = 10;

            @Config.Comment("Base Power Used Each time a radio transmits a packet (FE)")
            @Config.RangeInt(min = 0, max = 1000)
            public int basePowerPerProcess = 2;

            @Config.Comment("Encryption Card Cost Per Tick (additional FE/t per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int encryptionCardCostPerTick = 0;

            @Config.Comment("Encryption Card Cost Per Process (additional FE per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int encryptionCardCostPerProcess = 2;

            @Config.Comment("Stack Upgrade Cost Per Tick (additional FE/t per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int stackUpgradeCostPerTick = 0;

            @Config.Comment("Stack Upgrade Cost Per Process (additional FE per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int stackUpgradeCostPerProcess = 2;

            @Config.Comment("Stack Downgrade Cost Per Tick (additional FE/t per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int stackDowngradeCostPerTick = 0;

            @Config.Comment("Stack Downgrade Cost Per Process (additional FE per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int stackDowngradeCostPerProcess = 2;

            @Config.Comment("Speed Upgrade Cost Per Tick (additional FE/t per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int speedUpgradeCostPerTick = 0;

            @Config.Comment("Speed Upgrade Cost Per Process (additional FE per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int speedUpgradeCostPerProcess = 2;
        }
        public RXController rx_controller = new RXController();
        public static class RXController {
            @Config.Comment("Base Constant Power Usage of RX Controller (FE/t)")
            @Config.RangeInt(min = 0, max = 1000)
            public int basePowerPerTick = 10;

            @Config.Comment("Base Power Used Each time a radio receives a packet (FE)")
            @Config.RangeInt(min = 0, max = 1000)
            public int basePowerPerProcess = 2;

            @Config.Comment("Encryption Card Cost Per Tick (additional FE/t per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int encryptionCardCostPerTick = 0;

            @Config.Comment("Encryption Card Cost Per Process (additional FE per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int encryptionCardCostPerProcess = 2;

            @Config.Comment("Filter Card Cost Per Tick (additional FE/t per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int filterCardCostPerTick = 0;

            @Config.Comment("Filter Card Cost Per Process (additional FE per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int filterCardCostPerProcess = 2;
        }
        public ItemEncoder item_encoder = new ItemEncoder();
        public static class ItemEncoder {
            @Config.Comment("Base Constant Power Usage of Item Encoder (FE/t)")
            @Config.RangeInt(min = 0, max = 1000)
            public int basePowerPerTick = 10;

            @Config.Comment("Base Power Used Each time an item encoder processes an item (FE)")
            @Config.RangeInt(min = 0, max = 1000)
            public int basePowerPerProcess = 2;

            @Config.Comment("Speed Upgrade Cost Per Tick (additional FE/t per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int speedUpgradeCostPerTick = 0;

            @Config.Comment("Speed Upgrade Cost Per Process (additional FE per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int speedUpgradeCostPerProcess = 2;
        }
        public ItemDecoder item_decoder = new ItemDecoder();
        public static class ItemDecoder {
            @Config.Comment("Base Constant Power Usage of Item Decoder (FE/t)")
            @Config.RangeInt(min = 0, max = 1000)
            public int basePowerPerTick = 10;

            @Config.Comment("Base Power Used Each time an item decoder processes an item (FE)")
            @Config.RangeInt(min = 0, max = 1000)
            public int basePowerPerProcess = 2;

            @Config.Comment("Speed Upgrade Cost Per Tick (additional FE/t per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int speedUpgradeCostPerTick = 0;

            @Config.Comment("Speed Upgrade Cost Per Process (additional FE per upgrade)")
            @Config.RangeInt(min = 0, max = 1000)
            public int speedUpgradeCostPerProcess = 2;
        }
    }
}
